variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -U -P shade"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - build
  - build-plugin

# For merge requests do .bitlnot `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
build-jar:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

package-jar:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
  only:
    - master
  artifacts:
    paths:
      - 'taxi-lang-server-standalone/target/taxi-lang-server-standalone.jar'
    
package-plugin:
  image: node:13
  stage: build-plugin
  script:
    - 'cd vscode-extension'
    - 'npm install'
    - 'npm install -g vsce semantic-release'
    - 'npx semantic-release'
  only:
    - master
  artifacts:
    paths:
      - 'vscode-extension/*.vsix'