version: "3.3"
services:
   vyne:
      image: vyneco/vyne:${VYNE_VERSION:-latest-snapshot}
      environment:
         OPTIONS: >-
            --vyne.newSchemaSubmissionEnabled=true
            --eureka.uri=http://eureka
            --eureka.instance.preferIpAddress=true
            --server.port=80
            --management.endpoints.web.exposure.include=metrics,info,health,logfile,loggers
            --vyne.analytics.mode=InProcess
            --vyne.analytics.persistRemoteCallResponses=true
            --vyne.analytics.persistResults=true
            --vyne.schema.publicationMethod=RSOCKET
            --vyne.schema.consumptionMethod=RSOCKET
            --vyne.schema.management.KeepAliveStrategyId=RSocket
      expose:
         - 80
      ports:
         - "9022:80"
      volumes:
         - ~/.vyne/license:/opt/var/vyne/license
         - ./vyne/config:/opt/service/config

   schema-server:
      image: vyneco/schema-server:${VYNE_VERSION:-latest-snapshot}
      depends_on:
         - eureka
      volumes:
         - ${SCHEMA_PATH:-./vyne/schema-server}:/var/lib/vyne/schema-server
      environment:
         OPTIONS: >-
            --server.port=80
            --vyne.repositories.config-file=/var/lib/vyne/schema-server/schema-server.conf
            --eureka.uri=http://eureka
            --eureka.instance.preferIpAddress=true
      expose:
         - 80

   eureka:
      image: vyneco/eureka:${VYNE_VERSION:-latest-snapshot}
      environment:
         OPTIONS: >-
            --server.port=80
            --spring.main.banner-mode=off
            --eureka.instance.preferIpAddress=true
      expose:
         - 80
      ports:
         - "8761:80"
